baseurl = "https:cautiouslycurious/"
languageCode = "en-us"
title = "Cautiously Curious"
theme = "castanet"
themesdir = "../.."
paginate = "3"
buildFuture = true
#favicon = "/img/ico.png" #has to be 16x16px
#googleAnalytics = ""

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[permalinks]
	page = "/:filename/"
	about = "/:filename/"
	episode = "/:filename/"


# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
# The menus are sorted based upon their identifier

[[Menu.Main]]
    name = "Blog"
    identifier = "A"
    url = "/blog"

[[Menu.Main]]
    name = "Contact"
    identifier = "contact"
    url = "https://github.com/rastacalavera/cautiously-curious-HCN/issues/new/choose"

#[[Menu.Main]]
#    name = "Resources"
#    identifier = "resources"
#    url = "#!"
#[[Menu.Main]]
#    name = "Books"
#    identifier = "book"
#    url = "/books"
#    parent = "resources"
#[[Menu.Main]]
#    name = "Podcasts"
#    identifier = "podcast"
#    url = "/podcast"
#    parent = "resources"

#[[Menu.Main]]
#    name = "About"
#    identifier = "about"
#    url = "/about"

#[[Menu.Main]]
#    name = "Hosts"
#    identifier = "hosts"
#    url = "/host"

#[[Menu.Main]]
#    name = "Guests"
#    identifier = "guests"
#    url = "/guest"

#[[Menu.Main]]
#    name = "Upcoming Episodes"
#    identifier = "upcoming"
#    url = "/upcoming"

[params]
mainSections = ["episode"]
episode_number_style  = "brackets"
episode_number_prefix = "CWC"
site_theme = "blue"
site_layout = "row" #row/grid, if grid: jumbo is enabled and cannot be disabled, no sidebar
show_next_upcoming = "true"
enable_jumbo = "true" #true/false, if false, info in the jumbo gets placed in a left sidebar below episodes
disable_title_caps = "true"
copyright_notice = "Copyright 2022 Cautiously Curious"
description = "## This is a description field" #markdown ok
media_prefix = "https://cautiouslycurious.com/" #The URL to pre-pend to your podcast files. Must end in a slash.	
#googleAnalytics_UA = ""
# truncate = "100"
# about_logo = "/img/logo1400x1400.png" #	The logo (250px x 250px) you would like to appear on your About page. If not set, this will default to your Apple Podcasts image. This path should be relative to your main URL, for example, a file put in your static directory. This path should not start with a /.
#youtube_subscribe = "https://www.youtube.com/arresteddevops?sub_confirmation=1"
#itunes_subscribe = "https://podcasts.apple.com/us/podcast/arrested-devops/id773888088?ign-mpt=uo%3D4&mt=2"
#android_subscribe = "http://subscribeonandroid.com/feeds.podtrac.com/VGAulpN7MY1U"
#spotify_subscribe = "https://open.spotify.com/show/..."
#google_play_subscribe = "https://podcasts.google.com/feed/aHR0cHM6Ly93d3cuYXJyZXN0ZWRkZXZvcHMuY29tL2VwaXNvZGUvaW5kZXgueG1s"
#stitcher_subscribe = "http://www.stitcher.com/podcast/arrested-devops-2/arrested-devops"
#soundcloud_subscribe = "http://feeds.soundcloud.com/users/soundcloud:users:203144248/sounds.rss"
#pocketcasts_subscribe = "http://pcasts.in/feed/feeds.soundcloud.com/users/soundcloud:users:203144248/sounds.rss"
#mailchimp_subscribe = "//arresteddevops.us3.list-manage.com/subscribe/post?u=5e4cbcac996bb9df25f970a89&amp;id=154fa76bcc"
# rss_subscribe = "http://feed.com/myfeed" #only set this if you don't want to use the built-in feed
#disqusShortname = ""

  [params.feed]
    copyright = "Copyright 2022 Cautiously Curious" #do not use markdown in this field; it is used in the feed
    #itunes_subtitle = "The best podcast ever" #no markdown or HTML
    itunes_author = "Rastacalavera" #no markdown or HTML
    itunes_summary = "Two dudes dip a toe." # Limited to 4000 characters or less, plain text, no HTML
    itunes_owner_name = "rastacalavera"
    itunes_owner_email = "rastacalavera@protonmail.me" #contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on Apple Podcasts. It will not be publicly displayed on Apple Podcasts.
    itunes_image = "" #fqdn to the image art for your podcast
    itunes_top_category = "Technology"
    itunes_first_sub_category = "Education"
    #itunes_second_sub_category = "Tech News"
    language = "en-us"

  [params.realfavicongenerator] # https://realfavicongenerator.net/
    mask_icon_color="#5bbad5"
    msapplication_tilecolor="#2b5797"
    theme_color="#ffffff"

  # Social links can be given in full URL form or short form
  # In the short form the theme will generate a relevant URL
  # Appear in the top right of the screen
  [params.social]
    github = "rastacalavera"
    gitlab = "rastacalavera"
    #twitter = "https://twitter.com/rastacalavera"

#this can show images of all the "hosts". I've pointed it to the main logo
  [params.authors]
    [params.authors.x]
      name	= ""
      thumbnail = "img/logo1400x1400.png"
      bio = ""
      [params.authors.x.social]
        github = ""
        gitlab = ""
        twitter = ""
