baseURL = 'https://cautiouslycurious.com'
languageCode = 'en-us'
title = 'Cautiously Curious'
theme = "castanet"
googleAnalytics = ""
#themesdir = "../.."
paginate = "9" #If you are using the grid layout, you need to ensure that your pagination is set to a multiple of 3. For example, in your config file:
buildFuture = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[permalinks]
	# page = "/:filename/"
	about = "/:filename/"
	episode = "/:filename/"


# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
# The menus are sorted based upon their identifier
#This must be set.
[[Menu.Main]]
    name = "About"
    identifier = "about"
    url = "/about"

[[Menu.Main]]
    name = "Contact"
    identifier = "contact"
    url = "/contact"

[[Menu.Main]]
    name = "Hosts"
    identifier = "hosts"
    url = "/host"

# [[Menu.Main]]
#     name = "Guests"
#     identifier = "guests"
#     url = "/guest"

[[Menu.Main]]
    name = "Upcoming Episodes"
    identifier = "upcoming"
    url = "/upcoming"

[[Menu.Main]]
    name = "Blog"
    identifier = "blog"
    url = "/blog"

# [[Menu.Main]]
#     name = "Resources"
#     identifier = "resources"
#     url = "#!"

# [[Menu.Main]]
#     name = "Books"
#     identifier = "books"
#     url = "/books"
#     parent = "resources"
# [[Menu.Main]]
#     name = "Podcasts"
#     identifier = "podcasts"
#     url = "/books"
#     parent = "resources"
# [[Menu.Main]]
#     name = "Internet"
#     identifier = "internet"
#     url = "https://www.google.com"

[params]
googleAnalytics_UA = ""
mainSections = ["episode"]
episode_number_style  = "brackets" #not required,The format used for episode numbers in the episode's RSS feed. The choices are either parens, dash or brackets. If not set, the episode title in the RSS feed will just default to the title of the episode, without any episode number included.
episode_number_prefix = "CWC" #not required, A prefix used in the episode's RSS feed before the episode number. For example, if episode_number_prefix was set to CWC for episode 1, then the output might be Title of the Episode - CWC1.
site_theme = "blue" #Tnot required,the color scheme for the overall site. Currently the options are orange (default), grey, and blue.
site_layout = "row" #not required, The layout for the home page. The options are row (default) or grid.
#custom_css = [""] #not required, Array of custom CSS files for over-riding theme settings or adding your own classes. These files should be put into your static directory (not the static directory of the theme).
show_next_upcoming = "true" #not required, If there are episodes with the upcoming frontmatter set to true, then it will display the next episode on homepage. This halves the screen real estate of the latest episode section, which will then be displayed side by side.
enable_jumbo = "true" #not required, When using the row layout, will set a jumbotron at the top instead of the sidebar.
disable_title_caps = "true" # not required, When generating the RSS XML file do not convert the episode title to Title Case (using Title Case is the default)
# truncate = "100" #not required, The number of characters to truncate the summary on the row layout. This can be overridden per-episode as well. The default value (if not set) is 600 characters.
# about_logo = "/img/hugocast.png" #not required, The logo (250px x 250px) you would like to appear on your About page. If not set, this will default to your Apple Podcasts image. This path should be relative to your main URL, for example, a file put in your static directory. This path should not start with a /.
#favicon = "" #not required, The favicon file you would like to use for your site. If not set, this will default to the file icons/favicon.ico. This file should be put into your static directory (not the static directory of the theme).
copyright_notice = "Copyright 2022" #required, Your copyright information for the footer of the page. Can contain Markdown.
#youtube_subscribe = "https://www.youtube.com/"
#itunes_subscribe = "" #not required, The URL of your podcast in the Apple Podcasts store.
#android_subscribe = "" #not required,The URL for your podcast for Android users. You can generate this URL at Subscribe on Android.
spotify_subscribe = "https://open.spotify.com/show/..."
#google_play_subscribe = "" #not required,The URL to your podcast in Google Podcasts
#stitcher_subscribe = "" #not required, The URL to your podcast on Stitcher.
#soundcloud_subscribe = "" #not required, The URL to your podcast's feed on Soundcloud
# pocketcasts_subscribe = "" #not required, #The URL to your podcast's feed on Pocketcasts
#mailchimp_subscribe = "" #not required, The URL for your MailChimp signup form. This can be acquired from creating a "Super Slim" Embedded form on MailChimp. Do NOT include the entire form HTML; you just need the path for the form action.
# rss_subscribe = "" #not required, Optional parameter to over-ride the RSS feed URL, in case you use something like Feedburner. You likely do NOT need to set this parameter unless you have a very good reason to do so.
description = "CHANGE ME for the Description" #required, Description of your show. Can use Markdown.
media_prefix = "https://cautiouslycurious.com/" #required, The URL to pre-pend to your podcast files. Must end in a slash.
#disqusShortname = "" #not required, The shortname for use in Disqus comments. Example: "arresteddevops". Note: The Disqus comments will not appear if you are running on localhost.

  [params.feed]
    copyright = "Copyright 2022 Cautiously Curious" #required, do not use markdown in this field; it is used in the feed
    itunes_subtitle = "Come Cautiously Explore With Us" #not required, no markdown or HTML
    itunes_author = "Rastacalavera" #required, no markdown or HTML
    itunes_summary = "Two friends stumble through various topics as they look to expand their horizons." #required, Limited to 4000 characters or less, plain text, no HTML
    itunes_owner_name = "Rastacalavera" #required, The name associated with the owner of the podcast on Apple Podcasts. Will not be displayed publicly on Apple Podcasts.
    itunes_owner_email = "mrastacalavera@proton.me" #required, contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on Apple Podcasts. It will not be publicly displayed on Apple Podcasts.
    itunes_image = "https://www.arresteddevops.com/img/ado-podcast-logo.png" #required, Fully qualified path to your podcast's artwork for Apple Podcasts. Must conform to the Apple Podcasts image requirements, and be a JPG or PNG with a minimum of 1400 x 1400 pixels and a maximum of 3000 x 3000 pixesls, fqdn to the image art for your podcast
    itunes_top_category = "Education" #required
    itunes_first_sub_category = "Technology" #not required
    itunes_second_sub_category = "How-To" #not required
    # explicit = "no" #Whether or not the podcast itself contains explicit content (can also be set on a per-episode basis, see below). Default value from the archetype is "no". Valid values are "yes", "no", or "clean"
    language = "en-us"
#all of the favicon stuff is NOT required
  [params.realfavicongenerator] # https://realfavicongenerator.net/
    mask_icon_color="#5bbad5"
    msapplication_tilecolor="#2b5797"
    theme_color="#ffffff"
#podlove stuff is NOT required
#   [params.podlove] # https://subscribe-button.podlove.org
#     subscribe_title = ""              # fallback: site title from above
#     subscribe_subtitle = ""           # fallback: ""
#     subscribe_description = ""        # fallback: ""
#     subscribe_cover = "img/logo.jpg"  # fallback: ""
#     subscribe_color = "#585e6c"       # fallback: ""
#     subscribe_size = "medium"         # options: small, medium, big
#     subscribe_format = "rectangle"    # options: rectangle, square, cover
#     subscribe_style = "filled"        # options: filled, outline, frameless
#     subscribe_language = "de"         # options: nl (dutch), en (english), eo (esperanto), de (german), fi (finnish), fr (french), ja (french)
#     subscribe_feed_type = "audio"     # options: audio, video
#     subscribe_feed_format = "mp3"     # options: mp3, aac, ogg, opus

  # Social links can be given in full URL form or short form
  # In the short form the theme will generate a relevant URL
  # None of these are required
  [params.social]
    github = "rastacalavera"
    gitlab = "rastacalavera"
    #twitter = "https://twitter.com/arresteddevops"
    #twitter_domain = "arresteddevops.com" # This domain shows in twitter cards as "View on `twitter_domain`"
    # youtube = "arresteddevops"
    # Short form in linkedin will link to a user's page so use long form for company pages
#We use the "authors" from the configuration to list hosts in the jumbotron or sidebar. All hosts should have an entry in here. 
#These settings should be set under [params.authors] and then [params.authors.USERNAME] 

  [params.authors]
    [params.authors.RastaCalavera]
      name	= "RastaCalavera"
      thumbnail = "img/host/LLcover.png" #required, The image for the user. This can either be a fully qualifed URL, or relative to the baseURL.
      bio = "RC" #required, The author/host bio. Supports Markdown.
    #   pronouns = "" #not required
      [params.authors.RastaCalavera.social]
        github = "RastaCalavera"
        # facebook = "matt.stratton"
        # twitter = "mattstratton"
        # linkedin = "mattstratton"
        # homepage = "https://www.mattstratton.io"
        # pinterest = "mattstratton"
        # instagram = "instagram"
        # youtube = "mattstratton"
        # twitch = "mattstratton"
    [params.authors.Bill]
		name = "Bill B"
		thumbnail = "img/host/bill.jpg"
		bio = "BB"
		 [params.authors.Bill.social]
		#    twitter = ""
        #    instagram = "instagram"
    
    # To generate the list of links in the sidebar, you will set them in the config.toml similar to this:
    # [params.links]
    #   [params.links.ado]
    #     name = "Arrested DevOps"
    #     url = "https://www.arresteddevops.com"
    #   [params.links.ffs]
    #     name = "Food Fight Show"
    #     url = "https://foodfightshow.org"
    #   [params.links.sdt]
    #     name = "Software Defined Talk"
    #     url = "https://cote.io/podcasts/sdt/"
